name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag anotheridea/lait-cru-backend:latest

    - name: Log in to Docker registry
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Push image to Docker registry
      run: docker push anotheridea/lait-cru-backend:latest

  ssh-remote:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Restart docker on server
      uses: appleboy/ssh-action@master 
      with:
        host: ${{ secrets.SERVER_NAME }} 
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo cd /root/lait-cru.fr/ && sudo docker compose down && sudo docker pull anotheridea/lait-cru-backend:latest && sudo docker compose up -d